// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace GitterApp {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("GitterApp.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string LoginButtonText {
            get {
                return ResourceManager.GetString("LoginButtonText", resourceCulture);
            }
        }
        
        internal static string TaglineText {
            get {
                return ResourceManager.GetString("TaglineText", resourceCulture);
            }
        }
        
        internal static string LogoNameText {
            get {
                return ResourceManager.GetString("LogoNameText", resourceCulture);
            }
        }
        
        internal static string MenuGroupStarredUnreads {
            get {
                return ResourceManager.GetString("MenuGroupStarredUnreads", resourceCulture);
            }
        }
        
        internal static string MenuGroupUnreads {
            get {
                return ResourceManager.GetString("MenuGroupUnreads", resourceCulture);
            }
        }
        
        internal static string MenuGroupStarred {
            get {
                return ResourceManager.GetString("MenuGroupStarred", resourceCulture);
            }
        }
        
        internal static string MenuGroupRooms {
            get {
                return ResourceManager.GetString("MenuGroupRooms", resourceCulture);
            }
        }
        
        internal static string MenuGroupDirects {
            get {
                return ResourceManager.GetString("MenuGroupDirects", resourceCulture);
            }
        }
        
        internal static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        internal static string DoneButtonText {
            get {
                return ResourceManager.GetString("DoneButtonText", resourceCulture);
            }
        }
        
        internal static string MenuGroupSuggestions {
            get {
                return ResourceManager.GetString("MenuGroupSuggestions", resourceCulture);
            }
        }
        
        internal static string MenuGroupNoResults {
            get {
                return ResourceManager.GetString("MenuGroupNoResults", resourceCulture);
            }
        }
        
        internal static string MenuGroupSearchResults {
            get {
                return ResourceManager.GetString("MenuGroupSearchResults", resourceCulture);
            }
        }
    }
}
